# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

pool:
  vmImage: 'windows-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: MSBuild@1
  inputs:
    solution: '**/*.sln'

- task: CopyFiles@2
  inputs:
    Contents: '$(Build.BinariesDirectory)\bin\debug\*'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
- task: SqlAzureDacpacDeployment@1
  inputs:
    azureSubscription: 'e2edemo'
    AuthenticationType: 'connectionString'
    ConnectionString: 'Server=tcp:e2esqldbserver.database.windows.net,1433;Initial Catalog=e2esqldb;Persist Security Info=False;User ID=sqladmin;Password=admin@123;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;'
    deployType: 'DacpacTask'
    DeploymentAction: 'Publish'
    DacpacFile: '$(Build.ArtifactStagingDirectory)\e2edbdeployment.dacpac'
    IpDetectionMethod: 'AutoDetect'
